version: '3.8'


services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: roberto mora diaz 04
      POSTGRES_PASSWORD: futbolista
      POSTGRES_DB: proyectodb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data


volumes:
  postgres-data:

